### ISSUE TITLE
invalid signature: 0x6064b50 when zipping

### ISSUE THREAD

**Issue by raddevon** [serverless/serverless-babel-plugin#11]
I get `invalid signature: 0x6064b50` when the babel plugin tries to zip my compiled service. Here's the output:

```
Serverless: Packaging service...
Serverless: Babel compilation:
tmpBabelDirectory/functions/generateSchedule/index.js -> tmpBabelDirectory/functions/generateSchedule/index.js
tmpBabelDirectory/functions/getPostContent/index.js -> tmpBabelDirectory/functions/getPostContent/index.js
tmpBabelDirectory/functions/postToFB/handler.js -> tmpBabelDirectory/functions/postToFB/handler.js

Serverless: Packaging service with compiled files...

  Error --------------------------------------------------

     invalid signature: 0x6064b50

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Stack Trace --------------------------------------------

Error: invalid signature: 0x6064b50
    at /Users/raddevon/Documents/projects/resque/scheduler/node_modules/serverless-babel-plugin/node_modules/unzip2/lib/parse.js:63:13
    at processImmediate [as _immediateCallback] (timers.js:383:17)

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues

     Please report this error. We think it might be a bug.

  Your Environment Information -----------------------------
     OS:                 darwin
     Node Version:       4.4.3
     Serverless Version: 1.5.1
```

Is there a fix or workaround for this?

**Comment by mrosett** [comment]
I've run into this as well. Did you ever find a fix?

**Comment by raddevon** [comment]
@mrosett No. I ended up getting rid of the plugin.

**Comment by mrosett** [comment]
This seems to be the error when you haven't excluded aws-sdk from the package. I fixed it by adding this to serverless.yml

    package:
       exclude:
         - node_modules/aws-sdk/**

Note that you have access to aws-sdk by default when running on lambda, so you can exclude it from the package with no problems.

**Comment by nikgraf** [comment]
Does this still happen with the new released version 0.2.0?
